// Generated by CodiumAI




/*
Code Analysis

Main functionalities:
The Score class is responsible for calculating and keeping track of the player's score in a game. It calculates the score based on the velocity and angle of the player's movement and updates the total score accordingly. It also has a method to reset the total score to zero.

Methods:
- calculateScore(velocity: Vector, angle: number): This method takes in the player's velocity and angle and calculates the score based on the angle difference and velocity. It returns the calculated score.
- resetScore(): This method resets the total score to zero.

Fields:
- totalScore: This field keeps track of the player's total score.
- driftScore: This field is not used in the class and may be a leftover from previous versions or for future use.
- frameScore: This field is not used in the class and may be a leftover from previous versions or for future use.
*/


import {describe, expect, test, it} from '@jest/globals';
import Score from "../Score";
import Vector from "../../../utils/Vector";


describe('Score_class', () => {

    // Tests that the update method correctly updates the driftScore variable.
    it("test_update_method_updates_drift_score_correctly", () => {
        const score = new Score();
        const velocity = new Vector(1, 1);
        const angle = 0;
        score.update(velocity, angle);
        expect(score.driftScore).toBe(score.frameScore);
    });

    // Tests that the update method correctly updates the totalScore variable.
    it("test_update_method_updates_total_score_correctly", () => {
        const score = new Score();
        const velocity = new Vector(1, 1);
        const angle = 0;
        score.update(velocity, angle);
        let driftScore = score.driftScore;
        score.endDrift();
        expect(score.highScore).toBe(driftScore);
    });

    // Tests that the update method correctly handles the edge case where the velocity vector is 0.
    it("test_edge_case_velocity_is_0", () => {
        const score = new Score();
        const velocity = new Vector(0, 0);
        const angle = 0;
        score.update(velocity, angle);
        expect(score.frameScore).toBe(0);
    });

    // Tests that the endDrift method correctly resets the driftScore variable.
    it("test_end_drift_resets_drift_score_correctly", () => {
        const score = new Score();
        score.driftScore = 10;
        score.endDrift();
        expect(score.driftScore).toBe(0);
    });

    // Tests that the update method correctly calculates the frameScore variable.
    it("test_update_method_calculates_frame_score_correctly", () => {
        const score = new Score();
        const velocity = new Vector(1, 1);
        const angle = Math.PI / 4; // 45 degrees
        score.update(velocity, angle);
        expect(score.frameScore).toBeCloseTo(velocity.mag() * 0.29289321881); // expected value calculated manually
    });

    // Tests that the resetScore method correctly sets the totalScore variable to 0.
    it("test_reset_score_sets_total_score_to_0_correctly", () => {
        const score = new Score();
        score.highScore = 10;
        score.resetScore();
        expect(score.highScore).toBe(0);
    });

    // Tests that the update method correctly handles the edge case where the angle is 0 or 180 degrees.
    it("test_edge_case_angle_is_0_or_180_degrees", () => {
        // Arrange
        const score = new Score();
        const velocity = new Vector(5, 0);
        const angle = 0;

        // Act
        score.update(velocity, angle);

        // Assert
        expect(score.frameScore).toBe(0);
    });

    // Tests that the update method correctly handles the edge case where the angle is 90 degrees.
    it("test_edge_case_angle_is_90_degrees", () => {
        // Arrange
        const score = new Score();
        const velocity = new Vector(5, 0);
        const angle = Math.PI / 2;

        // Act
        score.update(velocity, angle);

        // Assert
        expect(score.frameScore).toBe(5);
    });

    // Tests that the update method correctly handles the edge case where the driftScore variable is already at its maximum value.
    it("test_edge_case_drift_score_is_already_at_maximum_value", () => {
        // Arrange
        const score = new Score();
        score.driftScore = Number.MAX_VALUE;
        const velocity = new Vector(5, 0);
        const angle = Math.PI / 4;

        // Act
        score.update(velocity, angle);

        // Assert
        expect(score.driftScore).toBe(Number.MAX_VALUE);
    });

});
