# .github/workflows/deploy.yml

name: Deploy Node.js App to Production

on:
  push:
    branches:
      - main  # Set your branch here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_SERVER_PORT }} ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP }} <<'ENDSSH'
        cd /home/cars/cars  # Set your app directory path here
        git pull
        npm run build
        sudo /bin/systemctl restart cars.service
        sudo /bin/systemctl restart cars-server.service  
        ENDSSH

